#!/usr/bin/env python3
"""Generate frozen oracle data for ScyPP tests from the reference SciPy.

Outputs (committed so CI runs without Python):
  tests/golden/golden.hpp        - input/expected vectors for special + constants
  src/constants/codata_table.inc - CODATA physical_constants table entries

Run:  python3 tests/oracle/generate.py
Refresh after touching the test set; review the diff before committing.
"""
import os
import numpy as np
import scipy.special as sps
import scipy.constants as spc
import scipy.linalg as sla
import scipy.fft as spf
import scipy.optimize as spo
import scipy.integrate as spi
import scipy.interpolate as spn
import scipy.stats as sst
import scipy.signal as ssg

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
GOLDEN = os.path.join(ROOT, "tests", "golden", "golden.hpp")
CODATA = os.path.join(ROOT, "src", "constants", "codata_table.inc")


def fmt(v):
    v = float(v)
    if np.isnan(v):
        return 'std::nan("")'
    if np.isinf(v):
        return "INFINITY" if v > 0 else "-INFINITY"
    return repr(v)


def emit_arr(out, name, xs, fn):
    ys = [fn(x) for x in xs]
    out.append(f"inline const double {name}_in[] = {{{', '.join(fmt(x) for x in xs)}}};")
    out.append(f"inline const double {name}_out[] = {{{', '.join(fmt(y) for y in ys)}}};")
    out.append(f"inline constexpr int {name}_n = {len(xs)};")


def emit_scalar(out, name, value):
    out.append(f"inline const double {name} = {fmt(value)};")


def emit_mat(out, name, m):
    """Emit a 2-D array (row-major) plus its dimensions."""
    m = np.asarray(m, dtype=float)
    r, c = (m.shape + (1,))[:2] if m.ndim == 2 else (m.shape[0], 1)
    flat = m.ravel()
    out.append(f"inline const double {name}_d[] = {{{', '.join(fmt(v) for v in flat)}}};")
    out.append(f"inline constexpr int {name}_r = {m.shape[0]};")
    out.append(f"inline constexpr int {name}_c = {m.shape[1] if m.ndim == 2 else 1};")


def main():
    out = ["#pragma once", "// AUTO-GENERATED by tests/oracle/generate.py from SciPy. Do not edit.",
           "#include <cmath>", "namespace golden {"]

    # ---- gamma family ----
    emit_arr(out, "gamma", [0.5, 1.0, 1.5, 2.5, 5.0, 10.0, -0.5, -1.5], sps.gamma)
    emit_arr(out, "gammaln", [0.5, 1.5, 2.5, 5.0, 10.0, 100.0], sps.gammaln)
    emit_arr(out, "digamma", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.digamma)
    emit_arr(out, "polygamma1", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(1, x))
    emit_arr(out, "polygamma2", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(2, x))
    emit_scalar(out, "beta_2_3", sps.beta(2, 3))
    emit_scalar(out, "beta_05_25", sps.beta(0.5, 2.5))
    emit_scalar(out, "betaln_2_3", sps.betaln(2, 3))
    emit_scalar(out, "betaln_10_20", sps.betaln(10, 20))

    # ---- error functions ----
    emit_arr(out, "erf", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erf)
    emit_arr(out, "erfc", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erfc)
    emit_arr(out, "erfinv", [-0.9, -0.5, 0.0, 0.5, 0.9, 0.99], sps.erfinv)
    emit_arr(out, "erfcinv", [0.1, 0.5, 1.0, 1.5, 1.9], sps.erfcinv)

    # ---- exponential integrals ----
    emit_arr(out, "exp1", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.exp1)
    emit_arr(out, "expi", [0.1, 0.5, 1.0, 2.0, 5.0], sps.expi)
    emit_arr(out, "expn2", [0.1, 0.5, 1.0, 2.0, 5.0], lambda x: sps.expn(2, x))
    emit_arr(out, "exprel", [-1.0, -0.001, 0.0, 0.001, 1.0, 5.0], sps.exprel)

    # ---- Bessel ----
    bx = [0.5, 1.0, 2.0, 5.0, 10.0]
    emit_arr(out, "jv0", bx, lambda x: sps.jv(0, x))
    emit_arr(out, "jv1", bx, lambda x: sps.jv(1, x))
    emit_arr(out, "jvhalf", bx, lambda x: sps.jv(0.5, x))
    emit_arr(out, "yv0", bx, lambda x: sps.yv(0, x))
    emit_arr(out, "yv1", bx, lambda x: sps.yv(1, x))
    emit_arr(out, "iv0", bx, lambda x: sps.iv(0, x))
    emit_arr(out, "iv1", bx, lambda x: sps.iv(1, x))
    emit_arr(out, "kv0", bx, lambda x: sps.kv(0, x))
    emit_arr(out, "kv1", bx, lambda x: sps.kv(1, x))
    emit_arr(out, "i0", bx, sps.i0)
    emit_arr(out, "i1", bx, sps.i1)
    emit_arr(out, "k0", bx, sps.k0)
    emit_arr(out, "k1", bx, sps.k1)

    # ---- orthogonal evaluators ----
    ox = [-1.0, -0.5, 0.0, 0.3, 0.7, 1.0]
    emit_arr(out, "legendre3", ox, lambda x: sps.eval_legendre(3, x))
    emit_arr(out, "legendre10", ox, lambda x: sps.eval_legendre(10, x))
    emit_arr(out, "chebyt4", ox, lambda x: sps.eval_chebyt(4, x))
    emit_arr(out, "chebyt7", ox, lambda x: sps.eval_chebyt(7, x))
    emit_arr(out, "hermite3", [-2.0, -1.0, 0.0, 0.5, 1.0, 2.0], lambda x: sps.eval_hermite(3, x))
    emit_arr(out, "laguerre3", [0.0, 0.5, 1.0, 2.0, 5.0], lambda x: sps.eval_laguerre(3, x))
    emit_arr(out, "genlag3", [0.0, 0.5, 1.0, 2.0, 5.0],
             lambda x: sps.eval_genlaguerre(3, 1.5, x))

    # ---- combinatorics ----
    emit_scalar(out, "comb_10_3", sps.comb(10, 3))
    emit_scalar(out, "comb_52_5", sps.comb(52, 5))
    emit_scalar(out, "perm_10_3", sps.perm(10, 3))
    emit_scalar(out, "fact_5", sps.factorial(5))
    emit_scalar(out, "fact_10", sps.factorial(10))

    # ---- reductions ----
    a1 = np.array([1.0, 2.0, 3.0, 4.0])
    emit_scalar(out, "lse_a1", sps.logsumexp(a1))
    sm = sps.softmax(a1)
    out.append(f"inline const double softmax_a1[] = {{{', '.join(fmt(v) for v in sm)}}};")
    big = np.array([1000.0, 1001.0, 1002.0])
    emit_scalar(out, "lse_big", sps.logsumexp(big))
    a2 = np.array([[1.0, 2.0, 3.0], [4.0, 6.0, 8.0]])
    lse_ax1 = sps.logsumexp(a2, axis=1)
    out.append(f"inline const double lse_a2_ax1[] = {{{', '.join(fmt(v) for v in lse_ax1)}}};")
    sm_ax1 = sps.softmax(a2, axis=1).ravel()
    out.append(f"inline const double softmax_a2_ax1[] = {{{', '.join(fmt(v) for v in sm_ax1)}}};")

    # ---- constants (stable / definition-based) ----
    for nm, val in [("c", spc.c), ("h", spc.h), ("hbar", spc.hbar), ("e", spc.e),
                    ("k", spc.k), ("N_A", spc.N_A), ("R", spc.R), ("g", spc.g),
                    ("pi", spc.pi), ("atm", spc.atm), ("bar", spc.bar),
                    ("inch", spc.inch), ("hour", spc.hour), ("eV", spc.eV)]:
        emit_scalar(out, f"const_{nm}", val)

    # physical_constants lookups under test
    for key, cname in [("electron mass", "electron_mass"),
                       ("proton mass", "proton_mass"),
                       ("Boltzmann constant", "boltzmann")]:
        v, u, unc = spc.physical_constants[key]
        emit_scalar(out, f"pc_{cname}_value", v)
        emit_scalar(out, f"pc_{cname}_prec", spc.precision(key))

    # temperature + wavelength conversions
    emit_scalar(out, "temp_c2f_100", spc.convert_temperature(100.0, "Celsius", "Fahrenheit"))
    emit_scalar(out, "temp_k2c_300", spc.convert_temperature(300.0, "Kelvin", "Celsius"))
    emit_scalar(out, "l2nu_500nm", spc.lambda2nu(500e-9))

    # ---- linalg ----
    Asq = np.array([[4., 3., 2., 1.], [3., 5., 1., 2.], [2., 1., 6., 3.], [1., 2., 3., 7.]])
    Aspd = np.array([[4., 1., 1.], [1., 3., 0.], [1., 0., 2.]])
    Atall = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 10.], [1., 0., 1.], [2., 1., 0.]])
    b4 = np.array([1., 2., 3., 4.])
    b5 = np.array([1., 2., 3., 4., 5.])
    emit_mat(out, "la_Asq", Asq)
    emit_mat(out, "la_Aspd", Aspd)
    emit_mat(out, "la_Atall", Atall)
    emit_mat(out, "la_b4", b4.reshape(-1, 1))
    emit_mat(out, "la_b5", b5.reshape(-1, 1))

    emit_scalar(out, "la_det_Asq", sla.det(Asq))
    emit_mat(out, "la_inv_Asq", sla.inv(Asq))
    emit_mat(out, "la_solve_Asq_b4", sla.solve(Asq, b4).reshape(-1, 1))
    emit_mat(out, "la_lstsq_x", sla.lstsq(Atall, b5)[0].reshape(-1, 1))
    emit_mat(out, "la_pinv_Atall", sla.pinv(Atall))
    emit_mat(out, "la_pinvh_Aspd", sla.pinvh(Aspd))
    emit_mat(out, "la_eigvalsh_Aspd", sla.eigvalsh(Aspd).reshape(-1, 1))
    emit_scalar(out, "la_norm_fro", sla.norm(Asq))
    emit_scalar(out, "la_norm_1", sla.norm(Asq, 1))
    emit_scalar(out, "la_norm_inf", sla.norm(Asq, np.inf))
    emit_mat(out, "la_chol_upper", sla.cholesky(Aspd))           # upper default
    emit_mat(out, "la_expm_Asq", sla.expm(Asq))
    emit_mat(out, "la_expm_rot", sla.expm(np.array([[0., 1.], [-1., 0.]])))
    pu, pp = sla.polar(Asq)
    emit_mat(out, "la_polar_u", pu)
    emit_mat(out, "la_polar_p", pp)

    # special matrices
    emit_mat(out, "la_toeplitz", sla.toeplitz([1., 2., 3., 4.]))
    emit_mat(out, "la_circulant", sla.circulant([1., 2., 3.]))
    emit_mat(out, "la_hankel", sla.hankel([1., 2., 3.], [3., 4., 5.]))
    emit_mat(out, "la_hilbert", sla.hilbert(4))
    emit_mat(out, "la_hadamard", sla.hadamard(4))
    emit_mat(out, "la_pascal", sla.pascal(4))
    emit_mat(out, "la_companion", sla.companion([1., -6., 11., -6.]))
    emit_mat(out, "la_tri", np.tril(np.ones((4, 4))))
    emit_mat(out, "la_leslie", sla.leslie([0.1, 2.0, 1.0, 0.1], [0.2, 0.8, 0.7]))
    emit_mat(out, "la_blockdiag", sla.block_diag(np.array([[1., 2.], [3., 4.]]),
                                                 np.array([[5.]]), np.array([[6., 7.]])))

    # ---- fft ----
    def emit_vec(name, arr):
        arr = np.asarray(arr, dtype=float).ravel()
        out.append(f"inline const double {name}[] = {{{', '.join(fmt(v) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    xr = np.array([1., 2., 3., 4., 5., 6., 7., 8.])
    emit_vec("fft_x", xr)
    F = spf.fft(xr)
    emit_vec("fft_re", F.real)
    emit_vec("fft_im", F.imag)
    Rf = spf.rfft(xr)
    emit_vec("rfft_re", Rf.real)
    emit_vec("rfft_im", Rf.imag)
    Fo = spf.fft(xr, norm="ortho")
    emit_vec("fft_ortho_re", Fo.real)
    emit_vec("fft_ortho_im", Fo.imag)

    for t in (1, 2, 3, 4):
        emit_vec(f"dct{t}", spf.dct(xr, type=t))
        emit_vec(f"dst{t}", spf.dst(xr, type=t))
        emit_vec(f"idct{t}", spf.idct(xr, type=t))
        emit_vec(f"idst{t}", spf.idst(xr, type=t))

    # dct along axis=0 of a 2-D array
    X2 = np.array([[1., 2., 3.], [4., 5., 6.]])
    emit_mat(out, "fft_X2", X2)
    emit_mat(out, "fft_dct2_ax0", spf.dct(X2, type=2, axis=0))

    emit_vec("fftfreq8", spf.fftfreq(8, 0.1))
    emit_vec("rfftfreq8", spf.rfftfreq(8, 0.1))
    emit_vec("fftshift8", spf.fftshift(np.arange(8.0)))
    for n in (1, 7, 8, 13, 100, 1000):
        emit_scalar(out, f"nfl_{n}", float(spf.next_fast_len(n)))

    # ---- optimize ----
    emit_scalar(out, "opt_brentq", spo.brentq(lambda x: x * x - 2.0, 0.0, 2.0))
    emit_scalar(out, "opt_bisect", spo.bisect(lambda x: x * x - 2.0, 0.0, 2.0))
    emit_scalar(out, "opt_newton", spo.newton(lambda x: x**3 - 2 * x - 5, 2.0))

    msb = spo.minimize_scalar(lambda x: np.cosh(x - 1.7), method="brent")
    emit_scalar(out, "opt_ms_brent_x", msb.x)
    emit_scalar(out, "opt_ms_brent_f", msb.fun)
    msd = spo.minimize_scalar(lambda x: (x - 2.0) ** 2, method="bounded", bounds=(0.0, 1.0))
    emit_scalar(out, "opt_ms_bounded_x", msd.x)

    def rosen(p):
        return (1 - p[0]) ** 2 + 100.0 * (p[1] - p[0] ** 2) ** 2
    nm = spo.minimize(rosen, [-1.2, 1.0], method="Nelder-Mead")
    emit_mat(out, "opt_nm_rosen", np.asarray(nm.x).reshape(-1, 1))

    quad = lambda p: (p[0] - 3.0) ** 2 + (p[1] + 1.0) ** 2
    bf = spo.minimize(quad, [0.0, 0.0], method="BFGS")
    emit_mat(out, "opt_bfgs_quad", np.asarray(bf.x).reshape(-1, 1))

    # curve_fit: a*exp(-b*x)+c, noise-free
    cf_x = np.linspace(0.0, 4.0, 20)
    cf_true = np.array([2.5, 1.3, 0.5])
    cf_y = cf_true[0] * np.exp(-cf_true[1] * cf_x) + cf_true[2]
    emit_vec("cf_xdata", cf_x)
    emit_vec("cf_ydata", cf_y)
    emit_mat(out, "opt_curvefit_true", cf_true.reshape(-1, 1))
    popt, _ = spo.curve_fit(lambda x, a, b, c: a * np.exp(-b * x) + c, cf_x, cf_y, p0=[1., 1., 1.])
    emit_mat(out, "opt_curvefit_popt", np.asarray(popt).reshape(-1, 1))

    # fsolve: x^2+y^2-4=0, x-y=0  -> (sqrt2, sqrt2)
    fs = spo.fsolve(lambda v: [v[0] ** 2 + v[1] ** 2 - 4.0, v[0] - v[1]], [1.0, 1.0])
    emit_mat(out, "opt_fsolve", np.asarray(fs).reshape(-1, 1))

    # ---- integrate ----
    # fixed-sample quadrature on an odd-length grid (even #intervals)
    ig_x = np.linspace(0.0, np.pi, 21)
    ig_y = np.sin(ig_x)
    emit_vec("ig_x", ig_x)
    emit_vec("ig_y", ig_y)
    emit_scalar(out, "ig_trapz", spi.trapezoid(ig_y, ig_x))
    emit_scalar(out, "ig_simpson", spi.simpson(ig_y, x=ig_x))
    emit_vec("ig_cumtrapz", spi.cumulative_trapezoid(ig_y, ig_x, initial=0.0))
    # adaptive quad: ∫_0^1 4/(1+x^2) dx = pi ; ∫_0^2 x^3 dx = 4
    emit_scalar(out, "ig_quad_pi", spi.quad(lambda x: 4.0 / (1.0 + x * x), 0.0, 1.0)[0])
    emit_scalar(out, "ig_quad_exp", spi.quad(lambda x: np.exp(-x * x), 0.0, 2.0)[0])
    emit_scalar(out, "ig_fixed_quad", spi.fixed_quad(lambda x: x**3, 0.0, 2.0, n=5)[0])

    # ---- interpolate ----
    ip_x = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
    ip_y = np.sin(ip_x)
    ip_q = np.linspace(0.2, 4.8, 12)
    emit_vec("ip_x", ip_x)
    emit_vec("ip_y", ip_y)
    emit_vec("ip_q", ip_q)
    emit_vec("ip_linear", spn.interp1d(ip_x, ip_y, kind="linear")(ip_q))
    emit_vec("ip_nearest", spn.interp1d(ip_x, ip_y, kind="nearest")(ip_q))
    emit_vec("ip_cubic", spn.CubicSpline(ip_x, ip_y)(ip_q))
    emit_vec("ip_cubic_d1", spn.CubicSpline(ip_x, ip_y)(ip_q, 1))
    emit_vec("ip_cubic_nat", spn.CubicSpline(ip_x, ip_y, bc_type="natural")(ip_q))
    emit_vec("ip_pchip", spn.PchipInterpolator(ip_x, ip_y)(ip_q))
    emit_vec("ip_akima", spn.Akima1DInterpolator(ip_x, ip_y)(ip_q))

    # 2-D regular grid
    gx = np.array([0.0, 1.0, 2.0, 3.0])
    gy = np.array([0.0, 1.0, 2.0])
    gv = np.array([[(xi * xi + yi) for yi in gy] for xi in gx])
    rgi_q = np.array([[0.5, 0.5], [1.5, 1.2], [2.7, 0.3], [3.0, 2.0]])
    emit_mat(out, "ip_gv", gv)
    emit_mat(out, "ip_rgi_q", rgi_q)
    emit_vec("ip_rgi_lin", spn.RegularGridInterpolator((gx, gy), gv, method="linear")(rgi_q))
    emit_vec("ip_rgi_near", spn.RegularGridInterpolator((gx, gy), gv, method="nearest")(rgi_q))

    # RBF scattered (2-D)
    rng = np.random.default_rng(0)
    yc = np.array([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0], [0.5, 0.5], [0.2, 0.8], [0.8, 0.3]])
    dvals = np.array([f(p) for p in yc for f in [lambda p: p[0] * p[0] + p[1]]])
    rbf_q = np.array([[0.3, 0.3], [0.6, 0.7], [0.9, 0.1]])
    emit_mat(out, "ip_rbf_y", yc)
    emit_vec("ip_rbf_d", dvals)
    emit_mat(out, "ip_rbf_q", rbf_q)
    emit_vec("ip_rbf_tps", spn.RBFInterpolator(yc, dvals, kernel="thin_plate_spline")(rbf_q))
    emit_vec("ip_rbf_cubic", spn.RBFInterpolator(yc, dvals, kernel="cubic")(rbf_q))
    emit_vec("ip_rbf_lin", spn.RBFInterpolator(yc, dvals, kernel="linear")(rbf_q))

    # ---- stats ----
    # distributions: pdf/cdf/ppf at points
    emit_scalar(out, "st_norm_pdf", sst.norm.pdf(0.7, loc=0.2, scale=1.5))
    emit_scalar(out, "st_norm_cdf", sst.norm.cdf(0.7, loc=0.2, scale=1.5))
    emit_scalar(out, "st_norm_ppf", sst.norm.ppf(0.83, loc=0.2, scale=1.5))
    emit_scalar(out, "st_gamma_cdf", sst.gamma.cdf(3.0, 2.5, scale=1.3))
    emit_scalar(out, "st_gamma_ppf", sst.gamma.ppf(0.6, 2.5, scale=1.3))
    emit_scalar(out, "st_chi2_cdf", sst.chi2.cdf(5.0, 3))
    emit_scalar(out, "st_chi2_sf", sst.chi2.sf(5.0, 3))
    emit_scalar(out, "st_beta_cdf", sst.beta.cdf(0.4, 2.0, 3.0))
    emit_scalar(out, "st_beta_ppf", sst.beta.ppf(0.7, 2.0, 3.0))
    emit_scalar(out, "st_t_cdf", sst.t.cdf(1.5, 8))
    emit_scalar(out, "st_t_ppf", sst.t.ppf(0.975, 8))
    emit_scalar(out, "st_f_cdf", sst.f.cdf(2.0, 5, 10))
    emit_scalar(out, "st_f_sf", sst.f.sf(2.0, 5, 10))
    emit_scalar(out, "st_expon_cdf", sst.expon.cdf(2.0, scale=1.5))

    # summary statistics
    sdat = np.array([2.0, 3.5, 1.0, 4.2, 2.8, 3.1, 5.0, 2.2, 3.3, 4.0])
    emit_vec("st_data", sdat)
    emit_scalar(out, "st_gmean", sst.gmean(sdat))
    emit_scalar(out, "st_hmean", sst.hmean(sdat))
    emit_scalar(out, "st_skew", sst.skew(sdat))
    emit_scalar(out, "st_kurtosis", sst.kurtosis(sdat))
    emit_scalar(out, "st_sem", sst.sem(sdat))
    emit_scalar(out, "st_variation", sst.variation(sdat))
    emit_scalar(out, "st_iqr", sst.iqr(sdat))
    tied = np.array([1.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0])
    emit_vec("st_tied", tied)
    emit_vec("st_rankdata", sst.rankdata(tied))
    emit_vec("st_zscore", sst.zscore(sdat))

    # correlation / regression
    cx = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
    cy = np.array([2.1, 3.9, 6.2, 7.8, 10.1, 12.2, 13.8])
    emit_vec("st_cx", cx); emit_vec("st_cy", cy)
    pr = sst.pearsonr(cx, cy)
    emit_scalar(out, "st_pearson_r", pr[0]); emit_scalar(out, "st_pearson_p", pr[1])
    spr = sst.spearmanr(cx, cy)
    emit_scalar(out, "st_spearman_r", spr.statistic); emit_scalar(out, "st_spearman_p", spr.pvalue)
    lr = sst.linregress(cx, cy)
    emit_scalar(out, "st_lr_slope", lr.slope); emit_scalar(out, "st_lr_intercept", lr.intercept)
    emit_scalar(out, "st_lr_r", lr.rvalue); emit_scalar(out, "st_lr_p", lr.pvalue)
    emit_scalar(out, "st_lr_stderr", lr.stderr)

    # hypothesis tests
    ga = np.array([5.1, 4.9, 6.2, 5.7, 5.5, 6.0, 4.8])
    gb = np.array([6.2, 6.8, 5.9, 7.1, 6.5, 6.9, 7.3])
    emit_vec("st_ga", ga); emit_vec("st_gb", gb)
    t1 = sst.ttest_1samp(ga, 5.0)
    emit_scalar(out, "st_t1_stat", t1.statistic); emit_scalar(out, "st_t1_p", t1.pvalue)
    ti = sst.ttest_ind(ga, gb)
    emit_scalar(out, "st_ti_stat", ti.statistic); emit_scalar(out, "st_ti_p", ti.pvalue)
    tr = sst.ttest_rel(ga, gb)
    emit_scalar(out, "st_tr_stat", tr.statistic); emit_scalar(out, "st_tr_p", tr.pvalue)
    gc = np.array([5.5, 5.8, 6.1, 5.9, 6.0, 5.7, 6.2])
    fo = sst.f_oneway(ga, gb, gc)
    emit_scalar(out, "st_fo_stat", fo.statistic); emit_scalar(out, "st_fo_p", fo.pvalue)
    ks = sst.ks_2samp(ga, gb, method="asymp")
    emit_scalar(out, "st_ks_stat", ks.statistic); emit_scalar(out, "st_ks_p", ks.pvalue)
    ct = np.array([[10.0, 20.0, 30.0], [6.0, 9.0, 17.0]])
    emit_mat(out, "st_ct", ct)
    c2 = sst.chi2_contingency(ct)
    emit_scalar(out, "st_chi2c_stat", c2.statistic); emit_scalar(out, "st_chi2c_p", c2.pvalue)
    emit_mat(out, "st_chi2c_exp", c2.expected_freq)
    nt_data = np.array([2.1, 3.4, 1.9, 5.2, 2.8, 3.3, 4.1, 2.5, 3.9, 2.2, 4.5, 3.0,
                        2.7, 3.6, 1.5, 4.8, 2.9, 3.2, 4.0, 2.6])
    emit_vec("st_nt_data", nt_data)
    ntr = sst.normaltest(nt_data)
    emit_scalar(out, "st_nt_stat", ntr.statistic); emit_scalar(out, "st_nt_p", ntr.pvalue)

    # gaussian_kde (1-D)
    kde_data = np.array([1.0, 1.5, 2.0, 2.2, 3.0, 3.1, 3.5, 4.0, 4.2, 5.0])
    kde_q = np.array([1.5, 2.5, 3.5, 4.5])
    emit_vec("st_kde_data", kde_data); emit_vec("st_kde_q", kde_q)
    emit_vec("st_kde_scott", sst.gaussian_kde(kde_data, bw_method="scott")(kde_q))
    emit_vec("st_kde_silverman", sst.gaussian_kde(kde_data, bw_method="silverman")(kde_q))

    # ---- signal ----
    sa = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    sb = np.array([0.5, 1.0, 0.5])
    emit_vec("sg_a", sa); emit_vec("sg_b", sb)
    emit_vec("sg_conv_full", ssg.convolve(sa, sb, mode="full"))
    emit_vec("sg_conv_same", ssg.convolve(sa, sb, mode="same"))
    emit_vec("sg_conv_valid", ssg.convolve(sa, sb, mode="valid"))
    emit_vec("sg_corr_full", ssg.correlate(sa, sb, mode="full"))

    emit_vec("sg_hann", ssg.windows.hann(16))
    emit_vec("sg_hamming", ssg.windows.hamming(16))
    emit_vec("sg_blackman", ssg.windows.blackman(16))
    emit_vec("sg_kaiser", ssg.windows.kaiser(16, 8.0))
    emit_vec("sg_tukey", ssg.windows.tukey(16, 0.5))
    emit_vec("sg_hann_per", ssg.windows.hann(16, sym=False))

    tw = np.linspace(0, 1, 50, endpoint=False)
    emit_vec("sg_tw", tw)
    emit_vec("sg_chirp", ssg.chirp(tw, f0=2.0, t1=1.0, f1=8.0, method="linear"))
    emit_vec("sg_sawtooth", ssg.sawtooth(2 * np.pi * 3 * tw))
    emit_vec("sg_square", ssg.square(2 * np.pi * 3 * tw, duty=0.3))

    # butter lowpass + filtering
    b, a = ssg.butter(4, 0.2, btype="low")
    emit_vec("sg_butter_b", b); emit_vec("sg_butter_a", a)
    bh, ah = ssg.butter(3, 0.3, btype="high")
    emit_vec("sg_butterhp_b", bh); emit_vec("sg_butterhp_a", ah)
    bbp, abp = ssg.butter(2, [0.2, 0.4], btype="band")
    emit_vec("sg_butterbp_b", bbp); emit_vec("sg_butterbp_a", abp)
    bc1, ac1 = ssg.cheby1(4, 1.0, 0.2, btype="low")
    emit_vec("sg_cheby1_b", bc1); emit_vec("sg_cheby1_a", ac1)
    bc2, ac2 = ssg.cheby2(4, 30.0, 0.2, btype="low")
    emit_vec("sg_cheby2_b", bc2); emit_vec("sg_cheby2_a", ac2)

    sig = np.sin(2 * np.pi * 3 * tw) + 0.4 * np.sin(2 * np.pi * 12 * tw)
    emit_vec("sg_sig", sig)
    emit_vec("sg_lfilter", ssg.lfilter(b, a, sig))
    emit_vec("sg_lfilter_zi", ssg.lfilter_zi(b, a))
    emit_vec("sg_filtfilt", ssg.filtfilt(b, a, sig))
    sos = ssg.butter(4, 0.2, btype="low", output="sos")
    emit_mat(out, "sg_sos", sos)
    emit_vec("sg_sosfilt", ssg.sosfilt(sos, sig))
    emit_vec("sg_detrend", ssg.detrend(sig, type="linear"))

    w, h = ssg.freqz(b, a, worN=32)
    emit_vec("sg_freqz_w", w)
    emit_vec("sg_freqz_hr", h.real); emit_vec("sg_freqz_hi", h.imag)
    hil = ssg.hilbert(sig)
    emit_vec("sg_hilbert_r", hil.real); emit_vec("sg_hilbert_i", hil.imag)

    taps = ssg.firwin(21, 0.3)
    emit_vec("sg_firwin", taps)

    fp, Pp = ssg.periodogram(sig, fs=50.0)
    emit_vec("sg_per_f", fp); emit_vec("sg_per_P", Pp)
    fw, Pw = ssg.welch(sig, fs=50.0, nperseg=16)
    emit_vec("sg_welch_f", fw); emit_vec("sg_welch_P", Pw)

    out.append("}  // namespace golden")
    os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
    with open(GOLDEN, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", GOLDEN)

    # ---- CODATA table ----
    lines = ["// AUTO-GENERATED by tests/oracle/generate.py from scipy.constants. Do not edit."]
    for key in sorted(spc.physical_constants):
        v, u, unc = spc.physical_constants[key]
        ek = key.replace("\\", "\\\\").replace('"', '\\"')
        eu = u.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{{"{ek}", {{{fmt(v)}, "{eu}", {fmt(unc)}}}}},')
    with open(CODATA, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", CODATA, f"({len(spc.physical_constants)} entries)")


if __name__ == "__main__":
    main()
