#!/usr/bin/env python3
"""Generate frozen oracle data for ScyPP tests from the reference SciPy.

Outputs (committed so CI runs without Python):
  tests/golden/golden.hpp        - input/expected vectors for special + constants
  src/constants/codata_table.inc - CODATA physical_constants table entries

Run:  python3 tests/oracle/generate.py
Refresh after touching the test set; review the diff before committing.
"""
import os
import numpy as np
import scipy.special as sps
import scipy.constants as spc
import scipy.linalg as sla
import scipy.fft as spf

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
GOLDEN = os.path.join(ROOT, "tests", "golden", "golden.hpp")
CODATA = os.path.join(ROOT, "src", "constants", "codata_table.inc")


def fmt(v):
    v = float(v)
    if np.isnan(v):
        return 'std::nan("")'
    if np.isinf(v):
        return "INFINITY" if v > 0 else "-INFINITY"
    return repr(v)


def emit_arr(out, name, xs, fn):
    ys = [fn(x) for x in xs]
    out.append(f"inline const double {name}_in[] = {{{', '.join(fmt(x) for x in xs)}}};")
    out.append(f"inline const double {name}_out[] = {{{', '.join(fmt(y) for y in ys)}}};")
    out.append(f"inline constexpr int {name}_n = {len(xs)};")


def emit_scalar(out, name, value):
    out.append(f"inline const double {name} = {fmt(value)};")


def emit_mat(out, name, m):
    """Emit a 2-D array (row-major) plus its dimensions."""
    m = np.asarray(m, dtype=float)
    r, c = (m.shape + (1,))[:2] if m.ndim == 2 else (m.shape[0], 1)
    flat = m.ravel()
    out.append(f"inline const double {name}_d[] = {{{', '.join(fmt(v) for v in flat)}}};")
    out.append(f"inline constexpr int {name}_r = {m.shape[0]};")
    out.append(f"inline constexpr int {name}_c = {m.shape[1] if m.ndim == 2 else 1};")


def main():
    out = ["#pragma once", "// AUTO-GENERATED by tests/oracle/generate.py from SciPy. Do not edit.",
           "#include <cmath>", "namespace golden {"]

    # ---- gamma family ----
    emit_arr(out, "gamma", [0.5, 1.0, 1.5, 2.5, 5.0, 10.0, -0.5, -1.5], sps.gamma)
    emit_arr(out, "gammaln", [0.5, 1.5, 2.5, 5.0, 10.0, 100.0], sps.gammaln)
    emit_arr(out, "digamma", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.digamma)
    emit_arr(out, "polygamma1", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(1, x))
    emit_arr(out, "polygamma2", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(2, x))
    emit_scalar(out, "beta_2_3", sps.beta(2, 3))
    emit_scalar(out, "beta_05_25", sps.beta(0.5, 2.5))
    emit_scalar(out, "betaln_2_3", sps.betaln(2, 3))
    emit_scalar(out, "betaln_10_20", sps.betaln(10, 20))

    # ---- error functions ----
    emit_arr(out, "erf", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erf)
    emit_arr(out, "erfc", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erfc)
    emit_arr(out, "erfinv", [-0.9, -0.5, 0.0, 0.5, 0.9, 0.99], sps.erfinv)
    emit_arr(out, "erfcinv", [0.1, 0.5, 1.0, 1.5, 1.9], sps.erfcinv)

    # ---- exponential integrals ----
    emit_arr(out, "exp1", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.exp1)
    emit_arr(out, "expi", [0.1, 0.5, 1.0, 2.0, 5.0], sps.expi)
    emit_arr(out, "expn2", [0.1, 0.5, 1.0, 2.0, 5.0], lambda x: sps.expn(2, x))
    emit_arr(out, "exprel", [-1.0, -0.001, 0.0, 0.001, 1.0, 5.0], sps.exprel)

    # ---- Bessel ----
    bx = [0.5, 1.0, 2.0, 5.0, 10.0]
    emit_arr(out, "jv0", bx, lambda x: sps.jv(0, x))
    emit_arr(out, "jv1", bx, lambda x: sps.jv(1, x))
    emit_arr(out, "jvhalf", bx, lambda x: sps.jv(0.5, x))
    emit_arr(out, "yv0", bx, lambda x: sps.yv(0, x))
    emit_arr(out, "yv1", bx, lambda x: sps.yv(1, x))
    emit_arr(out, "iv0", bx, lambda x: sps.iv(0, x))
    emit_arr(out, "iv1", bx, lambda x: sps.iv(1, x))
    emit_arr(out, "kv0", bx, lambda x: sps.kv(0, x))
    emit_arr(out, "kv1", bx, lambda x: sps.kv(1, x))
    emit_arr(out, "i0", bx, sps.i0)
    emit_arr(out, "i1", bx, sps.i1)
    emit_arr(out, "k0", bx, sps.k0)
    emit_arr(out, "k1", bx, sps.k1)

    # ---- orthogonal evaluators ----
    ox = [-1.0, -0.5, 0.0, 0.3, 0.7, 1.0]
    emit_arr(out, "legendre3", ox, lambda x: sps.eval_legendre(3, x))
    emit_arr(out, "legendre10", ox, lambda x: sps.eval_legendre(10, x))
    emit_arr(out, "chebyt4", ox, lambda x: sps.eval_chebyt(4, x))
    emit_arr(out, "chebyt7", ox, lambda x: sps.eval_chebyt(7, x))
    emit_arr(out, "hermite3", [-2.0, -1.0, 0.0, 0.5, 1.0, 2.0], lambda x: sps.eval_hermite(3, x))
    emit_arr(out, "laguerre3", [0.0, 0.5, 1.0, 2.0, 5.0], lambda x: sps.eval_laguerre(3, x))
    emit_arr(out, "genlag3", [0.0, 0.5, 1.0, 2.0, 5.0],
             lambda x: sps.eval_genlaguerre(3, 1.5, x))

    # ---- combinatorics ----
    emit_scalar(out, "comb_10_3", sps.comb(10, 3))
    emit_scalar(out, "comb_52_5", sps.comb(52, 5))
    emit_scalar(out, "perm_10_3", sps.perm(10, 3))
    emit_scalar(out, "fact_5", sps.factorial(5))
    emit_scalar(out, "fact_10", sps.factorial(10))

    # ---- reductions ----
    a1 = np.array([1.0, 2.0, 3.0, 4.0])
    emit_scalar(out, "lse_a1", sps.logsumexp(a1))
    sm = sps.softmax(a1)
    out.append(f"inline const double softmax_a1[] = {{{', '.join(fmt(v) for v in sm)}}};")
    big = np.array([1000.0, 1001.0, 1002.0])
    emit_scalar(out, "lse_big", sps.logsumexp(big))
    a2 = np.array([[1.0, 2.0, 3.0], [4.0, 6.0, 8.0]])
    lse_ax1 = sps.logsumexp(a2, axis=1)
    out.append(f"inline const double lse_a2_ax1[] = {{{', '.join(fmt(v) for v in lse_ax1)}}};")
    sm_ax1 = sps.softmax(a2, axis=1).ravel()
    out.append(f"inline const double softmax_a2_ax1[] = {{{', '.join(fmt(v) for v in sm_ax1)}}};")

    # ---- constants (stable / definition-based) ----
    for nm, val in [("c", spc.c), ("h", spc.h), ("hbar", spc.hbar), ("e", spc.e),
                    ("k", spc.k), ("N_A", spc.N_A), ("R", spc.R), ("g", spc.g),
                    ("pi", spc.pi), ("atm", spc.atm), ("bar", spc.bar),
                    ("inch", spc.inch), ("hour", spc.hour), ("eV", spc.eV)]:
        emit_scalar(out, f"const_{nm}", val)

    # physical_constants lookups under test
    for key, cname in [("electron mass", "electron_mass"),
                       ("proton mass", "proton_mass"),
                       ("Boltzmann constant", "boltzmann")]:
        v, u, unc = spc.physical_constants[key]
        emit_scalar(out, f"pc_{cname}_value", v)
        emit_scalar(out, f"pc_{cname}_prec", spc.precision(key))

    # temperature + wavelength conversions
    emit_scalar(out, "temp_c2f_100", spc.convert_temperature(100.0, "Celsius", "Fahrenheit"))
    emit_scalar(out, "temp_k2c_300", spc.convert_temperature(300.0, "Kelvin", "Celsius"))
    emit_scalar(out, "l2nu_500nm", spc.lambda2nu(500e-9))

    # ---- linalg ----
    Asq = np.array([[4., 3., 2., 1.], [3., 5., 1., 2.], [2., 1., 6., 3.], [1., 2., 3., 7.]])
    Aspd = np.array([[4., 1., 1.], [1., 3., 0.], [1., 0., 2.]])
    Atall = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 10.], [1., 0., 1.], [2., 1., 0.]])
    b4 = np.array([1., 2., 3., 4.])
    b5 = np.array([1., 2., 3., 4., 5.])
    emit_mat(out, "la_Asq", Asq)
    emit_mat(out, "la_Aspd", Aspd)
    emit_mat(out, "la_Atall", Atall)
    emit_mat(out, "la_b4", b4.reshape(-1, 1))
    emit_mat(out, "la_b5", b5.reshape(-1, 1))

    emit_scalar(out, "la_det_Asq", sla.det(Asq))
    emit_mat(out, "la_inv_Asq", sla.inv(Asq))
    emit_mat(out, "la_solve_Asq_b4", sla.solve(Asq, b4).reshape(-1, 1))
    emit_mat(out, "la_lstsq_x", sla.lstsq(Atall, b5)[0].reshape(-1, 1))
    emit_mat(out, "la_pinv_Atall", sla.pinv(Atall))
    emit_mat(out, "la_pinvh_Aspd", sla.pinvh(Aspd))
    emit_mat(out, "la_eigvalsh_Aspd", sla.eigvalsh(Aspd).reshape(-1, 1))
    emit_scalar(out, "la_norm_fro", sla.norm(Asq))
    emit_scalar(out, "la_norm_1", sla.norm(Asq, 1))
    emit_scalar(out, "la_norm_inf", sla.norm(Asq, np.inf))
    emit_mat(out, "la_chol_upper", sla.cholesky(Aspd))           # upper default
    emit_mat(out, "la_expm_Asq", sla.expm(Asq))
    emit_mat(out, "la_expm_rot", sla.expm(np.array([[0., 1.], [-1., 0.]])))
    pu, pp = sla.polar(Asq)
    emit_mat(out, "la_polar_u", pu)
    emit_mat(out, "la_polar_p", pp)

    # special matrices
    emit_mat(out, "la_toeplitz", sla.toeplitz([1., 2., 3., 4.]))
    emit_mat(out, "la_circulant", sla.circulant([1., 2., 3.]))
    emit_mat(out, "la_hankel", sla.hankel([1., 2., 3.], [3., 4., 5.]))
    emit_mat(out, "la_hilbert", sla.hilbert(4))
    emit_mat(out, "la_hadamard", sla.hadamard(4))
    emit_mat(out, "la_pascal", sla.pascal(4))
    emit_mat(out, "la_companion", sla.companion([1., -6., 11., -6.]))
    emit_mat(out, "la_tri", np.tril(np.ones((4, 4))))
    emit_mat(out, "la_leslie", sla.leslie([0.1, 2.0, 1.0, 0.1], [0.2, 0.8, 0.7]))
    emit_mat(out, "la_blockdiag", sla.block_diag(np.array([[1., 2.], [3., 4.]]),
                                                 np.array([[5.]]), np.array([[6., 7.]])))

    # ---- fft ----
    def emit_vec(name, arr):
        arr = np.asarray(arr, dtype=float).ravel()
        out.append(f"inline const double {name}[] = {{{', '.join(fmt(v) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    xr = np.array([1., 2., 3., 4., 5., 6., 7., 8.])
    emit_vec("fft_x", xr)
    F = spf.fft(xr)
    emit_vec("fft_re", F.real)
    emit_vec("fft_im", F.imag)
    Rf = spf.rfft(xr)
    emit_vec("rfft_re", Rf.real)
    emit_vec("rfft_im", Rf.imag)
    Fo = spf.fft(xr, norm="ortho")
    emit_vec("fft_ortho_re", Fo.real)
    emit_vec("fft_ortho_im", Fo.imag)

    for t in (1, 2, 3, 4):
        emit_vec(f"dct{t}", spf.dct(xr, type=t))
        emit_vec(f"dst{t}", spf.dst(xr, type=t))
        emit_vec(f"idct{t}", spf.idct(xr, type=t))
        emit_vec(f"idst{t}", spf.idst(xr, type=t))

    # dct along axis=0 of a 2-D array
    X2 = np.array([[1., 2., 3.], [4., 5., 6.]])
    emit_mat(out, "fft_X2", X2)
    emit_mat(out, "fft_dct2_ax0", spf.dct(X2, type=2, axis=0))

    emit_vec("fftfreq8", spf.fftfreq(8, 0.1))
    emit_vec("rfftfreq8", spf.rfftfreq(8, 0.1))
    emit_vec("fftshift8", spf.fftshift(np.arange(8.0)))
    for n in (1, 7, 8, 13, 100, 1000):
        emit_scalar(out, f"nfl_{n}", float(spf.next_fast_len(n)))

    out.append("}  // namespace golden")
    os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
    with open(GOLDEN, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", GOLDEN)

    # ---- CODATA table ----
    lines = ["// AUTO-GENERATED by tests/oracle/generate.py from scipy.constants. Do not edit."]
    for key in sorted(spc.physical_constants):
        v, u, unc = spc.physical_constants[key]
        ek = key.replace("\\", "\\\\").replace('"', '\\"')
        eu = u.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{{"{ek}", {{{fmt(v)}, "{eu}", {fmt(unc)}}}}},')
    with open(CODATA, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", CODATA, f"({len(spc.physical_constants)} entries)")


if __name__ == "__main__":
    main()
