#pragma once
// ScyPP umbrella header — Modern C++20 port of SciPy, built on NumPP.

#include "scypp/version.hpp"
#include "scypp/error.hpp"
#include "scypp/cluster/cluster.hpp"
#include "scypp/constants/constants.hpp"
#include "scypp/io/io.hpp"
#include "scypp/differentiate/differentiate.hpp"
#include "scypp/fft/fft.hpp"
#include "scypp/integrate/integrate.hpp"
#include "scypp/interpolate/interpolate.hpp"
#include "scypp/linalg/linalg.hpp"
#include "scypp/optimize/optimize.hpp"
#include "scypp/signal/signal.hpp"
#include "scypp/sparse/sparse.hpp"
#include "scypp/ndimage/ndimage.hpp"
#include "scypp/odr/odr.hpp"
#include "scypp/spatial/spatial.hpp"
#include "scypp/special/special.hpp"
#include "scypp/stats/stats.hpp"
